config/routes.rb
Rails.application.routes.draw do
  resources :instagram_wods, only: [:new, :create]
  resources :wodify_wods, only: [:new, :create]
  resources :wods, only: [:index, :show] do
    resources :logs
  end
  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      post 'create_maebashi_wod', to: 'maebashi_wods#create'
    end
  end
  root 'wods#index'
end

app/models/wod.rb
class Wod < ApplicationRecord

  attr_accessor :specified_date

  has_many :logs

  validates :date, presence: true
  validates :name, presence: true
  validates :content, presence: true
  validate :must_be_same_date_as_specified_date, if: :specified_date

  def create_from_html(html)
    attributes = WodExtraction.execute(html)
    if attributes.present?
      assign_attributes(attributes)
      save
    else
      true  # WODがない時はtrueで返してスキップする
    end
  end

  private

  def must_be_same_date_as_specified_date
    if date != specified_date
      errors[:base] << "指定したWodの日付と異なっています。"
    end
  end

  class WodExtraction
    WOD_DATE_ID = Rails.application.credentials.dig(:wodify, :html, :wod_date_id)
    NO_WOD_FOUND_TEXT = Rails.application.credentials.dig(:wodify, :html, :no_wod_found_text)
    ANNOUNCEMENT_ID = Rails.application.credentials.dig(:wodify, :html, :wod_announcement_id)
    MAIN_CONTENT_ID = Rails.application.credentials.dig(:wodify, :html, :wod_main_content_id)

    def self.execute(html)
      attributes = {}
      doc = Nokogiri::HTML.parse(html)
      displayed_date_str = doc.css("##{WOD_DATE_ID}").text
      Rails.logger.info("displayed_date_str: #{displayed_date_str}")
      if displayed_date_str == NO_WOD_FOUND_TEXT
        Rails.logger.info("Skipped this date because of no wod")
        return false
      end
      attributes[:date] = Date.parse(displayed_date_str)
      doc.css("##{ANNOUNCEMENT_ID}").remove
      attributes[:content] = doc.css("##{MAIN_CONTENT_ID}").inner_html.gsub(/\n/, "")
      attributes
    end
  end
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController
  def index
    @q = Wod.ransack(params[:q])
    @wod = @q.result(distinct: true).shuffle.first
  end

  def show
    @wod = Wod.find(params[:id])
    @logs = @wod.logs
  end
end

app/views/wods/index.html.erb
<h1>WOD一覧</h1>
<br><br>
<h2>WODを検索</h2>
<%= search_form_for @q do |f| %>
  <div class="form-group row">
      <%= f.label :date, "日付", class: 'col-2 col-form-label' %>
      <div class="col-10">
        <%= f.date_field :date_eq, class: 'form-control' %>
      </div>
  </div>
  <div class="form-group row">
    <%= f.label :content, "内容", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= f.search_field :content_i_cont, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit '検索', class: 'btn btn-dark btn-block' %>
<% end %>
<br><br>
<h2>ヒットしたWOD</h2>
<% if @wod.present? %>
  <%= render 'shared/wod_detail', wod: @wod %>

  <br><br>
  <div class="text-right">
    <%= link_to 'WOD詳細 >', wod_path(@wod), class: 'btn btn-secondary' %>
  </div>
<% else %>
  該当するWODはありません。
<% end %>

app/views/wods/show.html.erb
<%= link_to '< WOD一覧', wods_path, class: 'btn btn-secondary my-3' %>
<h1>WOD詳細</h1>
<%= render 'shared/wod_detail', wod: @wod %>

<h2>ログ</h2>
<% @logs.each do |log| %>
  <div class="row mt-3">
    <div class="col-8">
      <%= log.date %>
    </div>
    <div class="col-4">
      <%= link_to '詳細', wod_log_path(@wod, log), class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>
<%= link_to 'ログを追加', new_wod_log_path(@wod), class: 'btn btn-dark mt-3' %>