config/routes.rb
Rails.application.routes.draw do
  resources :instagram_wods, only: [:new, :create]
  resources :wodify_wods, only: [:new, :create]
  resources :wods, only: [:index, :show] do
    resources :logs
  end
  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      post 'create_maebashi_wod', to: 'maebashi_wods#create'
    end
  end
  root 'wods#index'
end

app/models/wodify_wod.rb
class WodifyWod

  SIGN_IN_URL = Rails.application.credentials.dig(:wodify, :sign_in_url)
  SIGN_IN_EMAIL = Rails.application.credentials.dig(:wodify, :email)
  SING_IN_USER_NAME_ID = Rails.application.credentials.dig(:wodify, :form, :sign_in_username_id)
  SING_IN_USER_NAME_PASSWORD = Rails.application.credentials.dig(:wodify, :form, :sign_in_password_id)
  SIGN_IN_PASSWORD = Rails.application.credentials.dig(:wodify, :password)
  SIGN_IN_BUTTON = Rails.application.credentials.dig(:wodify, :button, :sign_in)
  LOGOUT_BUTTON = Rails.application.credentials.dig(:wodify, :button, :logout)
  DATE_FORM_ID = Rails.application.credentials.dig(:wodify, :form, :wod_date_id)

  attr_accessor :session

  def initialize
    Capybara.register_driver :selenium do |app|
      options = ::Selenium::WebDriver::Chrome::Options.new

      options.add_argument('--no-sandbox')
      options.add_argument('--headless')
      options.add_argument('--disable-gpu')
      options.add_argument('--disable-dev-shm-usage')
      options.add_argument('--window-size=1680,1050')

      Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
    end
    Capybara.javascript_driver = :selenium
    Capybara.configure do |config|
      config.save_path = "tmp/screenshots/"
    end
    @session = Capybara::Session.new(:selenium)
  end

  # @param [String] email
  # @param [String] password
  # @param [Date] date_1
  # @param [Date] date_2
  def fetch_wods(email, password, date_1, date_2, &block)
    if !date_1.is_a?(Date) || !date_2.is_a?(Date)
      raise TypeError "date_1 and date_2 must be Date object", caller
    end
    if date_1 < date_2
      date_range = (date_1..date_2)
    else
      date_range = (date_2..date_1)
    end
    sign_in(email, password)
    date_range.each do |date|
      block.call(fetch_wod_html_on(date), date)
    end
    sign_out
  end

  # @param [Date] date
  def fetch_wod_html_on(date)
    unless date.is_a?(Date)
      raise TypeError, "date must be Date object", caller
    end
    set_date(date)
    extract_whole_html
  end

  private

  def sign_in(email, password)
    session.visit SIGN_IN_URL
    sleep(2)
    session.instance_eval do
      fill_in(SING_IN_USER_NAME_ID, with: email)
      fill_in(SING_IN_USER_NAME_PASSWORD, with: password)
      click_on(SIGN_IN_BUTTON)
      sleep(2)
    end
  end

  def set_date(date)
    session.instance_eval do
      fill_in(DATE_FORM_ID, with: date.strftime("%Y/%m/%d"))
      sleep(3)
    end
  end

  # @return [String]
  def extract_whole_html
    session.html
  end

  def sign_out
    session.instance_eval do
      click_on(LOGOUT_BUTTON)
      sleep(3)
    end
  end
end

app/controllers/wodify_wods_controller.rb
class WodifyWodsController < ApplicationController
  def new
  end

  def create
    wodify_wod_client = WodifyWod.new
    are_all_wods_saved = true
    Wod.transaction do
      wodify_wod_client.fetch_wods(
        wodify_wod_params[:email],
        wodify_wod_params[:password],
        Date.parse(wodify_wod_params[:date_1]),
        Date.parse(wodify_wod_params[:date_2])
      ) do |each_wod_html, date|
        wod = Wod.new(specified_date: date)
        logger.info("specified_date: #{date}")
        if wod.create_from_html(each_wod_html)
          logger.info("#{date}のWodが保存できました。")
        else
          are_all_wods_saved = false
          logger.error("#{date}のWodが保存に失敗しました。")
          logger.error(wod.errors.full_messages)
          raise ActiveRecord::Rollback
        end
      end
    end

    if are_all_wods_saved
      flash[:notice] = "全てのWodが保存できました。"
    else
      flash[:notice] = "Wodの保存に失敗しました。"
    end
    redirect_to new_wodify_wod_path
  end

  private
  def wodify_wod_params
    params.require(:wodify_wod).permit(:email, :password, :date_1, :date_2)
  end
end

app/views/wodify_wods/new.html.erb
<h1>WodifyのWodを検索</h1>
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %>
<%= form_with(scope: :wodify_wod, url: wodify_wods_path, local: true) do |form| %>
  <div class="form-group row">
    <%= form.label :email, "メールアドレス", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.email_field :email, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :password, "パスワード", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.password_field :password, class: 'form-control', required: true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :start_date, "開始日", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.date_field :date_1, class: 'form-control', value: Date.current %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :end_date, "終了日", class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.date_field :date_2, class: 'form-control', value: Date.current %>
    </div>
  </div>
  <%= form.submit '検索', class: 'btn btn-dark btn-block' %>
<% end %>

<br><br>
<%= link_to '＜ WOD一覧へ', wods_path, class: 'btn btn-secondary btn-block' %>