config/routes.rb
Rails.application.routes.draw do
  resources :instagram_wods, only: [:new, :create]
  resources :wodify_wods, only: [:new, :create]
  resources :wods, only: [:index, :show] do
    resources :logs
  end
  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      post 'create_maebashi_wod', to: 'maebashi_wods#create'
    end
  end
  root 'wods#index'
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :wod

  validates :date, presence: true
  validates :rate, numericality: { greater_than_or_equal_to: 0.5, less_than_or_equal_to: 5.0 }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def new
    @wod = Wod.find(params[:wod_id])
    @log = Log.new
  end

  def create
    @wod = Wod.find(params[:wod_id])
    @log = @wod.logs.build(log_params)
    if @log.save
      redirect_to wod_log_path(@wod, @log), notice: "ログを追加しました。"
    else
      render :new
    end
  end

  def show
    @wod = Wod.find(params[:wod_id])
    @log = @wod.logs.find(params[:id])
  end

  def edit
    @wod = Wod.find(params[:wod_id])
    @log = @wod.logs.find(params[:id])
  end

  def update
    @wod = Wod.find(params[:wod_id])
    @log = @wod.logs.find(params[:id])
    if @log.update(log_params)
      redirect_to wod_log_path(@wod, @log), notice: "ログを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @wod = Wod.find(params[:wod_id])
    @log = @wod.logs.find(params[:id])
    @log.destroy
    redirect_to wod_path(@wod), notice: "ログを削除しました。"
  end

  private

  def log_params
    params.require(:log).permit(:date, :result, :memo, :rate)
  end
end

app/views/logs/_form.html.erb
<%= form_with model: [wod, log], local: true do |f| %>
  <%= render 'shared/show_object_errors', object: log, object_name: 'log' %>

  <div class="form-group">
    <%= f.label :date, class: 'col-form-label' %>
    <div class="">
      <%= f.date_field :date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :result, class: 'col-form-label' %>
    <div class="">
      <%= f.text_area :result, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :rate, class: 'col-form-label' %>
    <div class="">
      <%= f.number_field :rate, min: 0.5, max: 5.0, step: 0.5, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :memo, class: 'col-form-label' %>
    <div class="">
      <%= f.text_area :memo, rows: 5, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit '登録する', class: 'btn btn-dark mb-5' %>
<% end %>

app/views/logs/edit.html.erb
<%= link_to '< WOD詳細', wod_path(@wod), class: 'btn btn-secondary my-3' %>
<h2>ログを編集する</h2>
<%= render 'form', wod: @wod, log: @log  %>

<h2>WOD詳細</h2>
<%= render 'shared/wod_detail', wod: @wod %>

app/views/logs/new.html.erb
<%= link_to '< WOD詳細', wod_path(@wod), class: 'btn btn-secondary my-3' %>
<h2>ログを追加する</h2>
<%= render 'form', wod: @wod, log: @log  %>

<h2>WOD詳細</h2>
<%= render 'shared/wod_detail', wod: @wod %>

app/views/logs/show.html.erb
<%= link_to '< WOD詳細', wod_path(@wod), class: 'btn btn-secondary my-3' %>

<h2>ログ詳細</h2>
<div>
  <h5>日付</h5>
  <div class="mb-5">
    <%= @log.date %>
  </div>

  <h5>結果</h5>
  <div class="mb-5">
    <%= @log.result %>
  </div>

  <h5>達成度</h5>
  <div class="mb-5">
    <%= @log.rate %>
  </div>

  <h5>感想</h5>
  <div class="mb-5">
    <%= @log.memo %>
  </div>
</div>

<div class="w-100 mb-5">
  <%= link_to '編集する', edit_wod_log_path(@wod,@log), class: 'btn btn-secondary' %>
  <%= link_to '削除する', wod_log_path(@wod,@log),  method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger float-right' %>
</div>

<h2>WOD詳細</h2>
<%= render 'shared/wod_detail', wod: @wod %>